/*
* generated by Xtext
*/
package com.github.fbrx.propertysl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PropertySLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.github.fbrx.propertysl.ui.internal.PropertySLActivator.getInstance().getInjector("com.github.fbrx.propertysl.PropertySL");
	}
	
}
