/*
 * generated by Xtext
 */
package com.github.fbrx.propertysl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.github.fbrx.propertysl.ui.internal.PropertySLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PropertySLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PropertySLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PropertySLActivator.getInstance().getInjector(PropertySLActivator.COM_GITHUB_FBRX_PROPERTYSL_PROPERTYSL);
	}
	
}
