/*
 * generated by Xtext
 */
package com.github.fbrx.propertysl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PropertySLUiModule extends com.github.fbrx.propertysl.ui.AbstractPropertySLUiModule {
	public PropertySLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
