/**
 * generated by Xtext
 */
package com.github.fbrx.propertysl.validation;

import com.github.fbrx.propertysl.validation.AbstractPropertySLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PropertySLValidator extends AbstractPropertySLValidator {
}
