grammar com.github.fbrx.PropertySL 
	with org.eclipse.xtext.common.Terminals

generate propertySL "http://www.github.com/fbrx/propertySL"

Model:
	packages += Package*;

Package:
	'package' ID '{'
		DefaultLocale?
		
		Property*
	'}'
;

Property:
	PropertyKey '=' PropertyValue
;

PropertyKey:
	'key'
;

PropertyValue:
	'value'
;

DefaultLocale:
	'DEFAULT_LOCALE' '=' LOCALE
;

LOCALE:
	'de' | 'en'
;

