/*
 * generated by Xtext
 */
package com.github.fbrx.propertysl.validation

import com.github.fbrx.propertysl.propertySL.Package
import com.github.fbrx.propertysl.propertySL.PropertySLPackage
import org.eclipse.xtext.validation.Check
import com.github.fbrx.propertysl.propertySL.ComplexPropertyValueItem
import com.github.fbrx.propertysl.propertySL.ComplexPropertyValue
import java.util.ArrayList

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class PropertySLValidator extends AbstractPropertySLValidator {


	@Check
	def checkIfDefaultLocaleIsSupported(Package pkg){
		if(pkg.defaultLocale != null){
			if(pkg.supportedLocales != null){
				if(!pkg.supportedLocales.locales.contains(pkg.defaultLocale.lang)){
					error("default locale must be one of supported locales", PropertySLPackage.Literals.PACKAGE__DEFAULT_LOCALE);
				}
			}else{
				warning("supported locales are not defined", PropertySLPackage.Literals.PACKAGE__DEFAULT_LOCALE)
			}
		}
	}
	
	@Check
	def checkLocaleOfComplexPropertyValue(ComplexPropertyValueItem item){
		val pkg = item.eContainer.eContainer.eContainer as Package
		if(!pkg.supportedLocales.locales.contains(item.lang)){
			warning("locale is not defined", PropertySLPackage.Literals.COMPLEX_PROPERTY_VALUE_ITEM__LANG)
		}
	}
	
	@Check
	def checkItemsOfComplexPropertyValue(ComplexPropertyValue prop){
		val pkg = prop.eContainer.eContainer as Package
		var languages = new ArrayList<String>;
		
		for(ComplexPropertyValueItem item : prop.items){
			languages.add(item.lang)
		}

		if(!languages.containsAll(pkg.supportedLocales.locales)){
			error("all supported locales must be specified", PropertySLPackage.Literals.COMPLEX_PROPERTY_VALUE__ITEMS)
		}
	}
	
}
