/*
 * generated by Xtext
 */
package com.github.fbrx.propertysl.ui.contentassist

import com.github.fbrx.propertysl.ui.contentassist.AbstractPropertySLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PropertySLProposalProvider extends AbstractPropertySLProposalProvider {
}
