/*
* generated by Xtext
*/
package com.github.fbrx.propertysl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.github.fbrx.propertysl.services.PropertySLGrammarAccess;

public class PropertySLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PropertySLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.github.fbrx.propertysl.parser.antlr.internal.InternalPropertySLParser createParser(XtextTokenStream stream) {
		return new com.github.fbrx.propertysl.parser.antlr.internal.InternalPropertySLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public PropertySLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PropertySLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
