/*
* generated by Xtext
*/
package com.github.fbrx.propertysl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PropertySLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/github/fbrx/propertysl/parser/antlr/internal/InternalPropertySL.tokens");
	}
}
