/*
* generated by Xtext
*/
package com.github.fbrx.propertysl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PropertySLStandaloneSetup extends PropertySLStandaloneSetupGenerated{

	public static void doSetup() {
		new PropertySLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

