/*
 * generated by Xtext
 */
package com.github.fbrx.propertysl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PropertySLRuntimeModule extends com.github.fbrx.propertysl.AbstractPropertySLRuntimeModule {

}
