/*
 * generated by Xtext
 */
package com.github.fbrx.propertysl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractPropertySLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.github.fbrx.propertysl.propertySL.PropertySLPackage.eINSTANCE);
		return result;
	}
}
